### ISSUE TITLE
Broken in PeerTube 3.0.1

### ISSUE THREAD

**Issue by kontrollanten** [kimsible/peertube-plugin-social-sharing#5]
Since [this commit](https://github.com/Chocobozzz/PeerTube/commit/f8b530e0a523a0d9ff469ef716838374c395a360#diff-558ca1dd6dd9a9099041e4eddf7bd57d89bee131372fffa5f3961f5595cb984b) PeerTube are using my-input-toggle-hidden instead of my-input-readonly-copy. That makes the following operation to break

https://github.com/kimsible/peertube-plugin-social-sharing/blob/ee707403d48709cd1a96e5dd4dff030184565e55/client/common-client-plugin.js#L49-L52

**Comment by scramblr** [comment]
This issue is still present, social sharing links are broken as of May 3rd 2021 - Peertube Release 3.1.0. Is there any plan to fix this?
